apiVersion: v1
kind: Service
metadata:
  name: servicauti
spec:
  selector:
    name: auti
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5000
    nodePort: 31494
    protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auti
  labels:
    name: auti
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auti
  template:
    metadata:
      labels:
        name: auti
    spec:
      containers:
      - name: auti
        image: mohamaddiwany/auti
        ports:
        - containerPort: 5000
      hostname: auti
